name: Reusable workflow

description: Checks if a secret exists

inputs:
  secret:
    description: 'Secret parameter to check'
    required: false

runs:
  using: 'bash'

  steps:
    - id: result
      run: |
        if ! [[ -z "${{ inputs.secret }}" ]]; then
          echo ::set-output has_token=true >> $GITHUB_OUTPUT
        else
          echo ::set-output has_token=false >> $GITHUB_OUTPUT
        fi
