name: Check Secret Existence

description: Check if a GitHub secret exists.

inputs:
  secret:
    description: 'The name of the secret to check.'
    required: true

outputs:
  has_token:
    value: ${{ steps.secret-check.outputs.has_token }}
    description: 'Indicates if the secret exists or not.'

runs:
  using: 'composite'
  steps:
    - name: Check Secret Existence
      id: secret-check
      run: |
        if [[ -n "${{ inputs.secret }}" ]]; then
          echo "::set-output name=has_token::true"
        else
          echo "::set-output name=has_token::false"
        fi
