name: Reusable workflow

description: Checks if a secret exists

inputs:
  secret:
    description: 'Secret parameter to check'
    required: false

outputs:
  exist:
    description: "The first output string"
    value: ${{ jobs.example_job.outputs.output.result }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.result.outputs.has_token }}
    steps:
      - id: result
        run: |
          if ! [[ -z "${{ inputs.secret }}" ]]; then
            echo ::set-output has_token=true >> $GITHUB_OUTPUT
          else
            echo ::set-output has_token=false >> $GITHUB_OUTPUT
          fi
