name: Deploy DEV API

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'My input'
        default: "my input value"
  push:
    branches:
      - next
      - main

jobs:
  check_token:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Check if secret exists
      id: secret-check
      uses: ./.github/actions/secret-exists
      with:
        secret: 123

  deploy_dev_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ check_token ]
    if: ${{ fromJson(needs.check_token.outputs.has_token) }}
    timeout-minutes: 80
    environment: Development
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        name: Clone Repo
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: Output Input Branch
        run: echo branch - "${{ github.ref_name }}"

      - name: Check if secret exists
        id: secret-check
        uses: ./.github/actions/secret-exists
        with:
          secret:

      - name: Display result
        run: |
          if [[ "${{ steps.secret-check.outputs.has_token }}" == "true" ]]; then
            echo "Secret exists."
          else
            echo "Secret does not exist."
          fi


      - name: Display result as is
        run: echo "${{ steps.secret-check.outputs }}"
